physics and rigidbody done, no tests
fabdan-8/GameEngine-D7049E pull request #13
Opened 2023-04-30 23:14 UTC by adededede

seems ok?

2023-05-03 15:45 UTC, vaneri-9 requested changes
It would be nice if you could write here how the physics system even works, what "hitboxes" does it use, what's the difference between soft and hard bodies (even though it seems that right now there's only hard bodies coded).

2023-05-03 15:45 UTC, vaneri-9 commented on src/Physics.h
> +    void update(int timeSinceLastFrame);
You should probably in GameEngine add a new field for the variable you use here and in the MainGameLoop update that variable every iteration (or just use a pointer).


Then calling Update() should be possible (without the usage of an input parameter)

2023-05-03 15:45 UTC, vaneri-9 commented on src/Physics.cpp
> +Physics::Physics(float gravityX, float gravityY, float gravityZ ) {
For earths gravity what would be the defaults? (0,0,9.82)?

2023-05-05 12:56 UTC, adededede commented on src/Physics.cpp
> +Physics::Physics(float gravityX, float gravityY, float gravityZ ) {
nope I wrote it in the comment of the cpp file it's 0, -9.82, 0
Maybe I should change the name of the variable it's more the forces expressed on each axes

2023-05-05 13:03 UTC, adededede commented on src/Physics.h
> +    void update(int timeSinceLastFrame);
okay i'll look into it but then the new field in GameEngine need to be public

2023-05-05 13:05 UTC, adededede commented
I feel like I explained it within the commentary of the cpp file, but if they weren't enough I can still add some explanation here of course

2023-05-11 08:53 UTC, merged